### ISSUE TITLE
Embedded Lua

### ISSUE THREAD

**Issue by lemnext** [leafo/moonscript#126]
A way of intersperse snippets of Lua within Moonscript would be sometimes quite useful, as it is possible with backticks in CoffeeScript.

**Comment by ChickenNuggers** [comment]
We could use <code>``</code> as operators for this.

Example:

```moonscript
lshift = val1 `<<` val2
```

Unless it's already used; in that case, we could use `$$`? This is something that I've actually been wanting in MoonScript yet never found an issue for it.

**Comment by missingnumber** [comment]
ChickenNuggers: How would that work exactly? It seems like Moonscript needs to know '<<' is an operator to make sense of it.

**Comment by ChickenNuggers** [comment]
@missingnumber Not really; it's like a string. You only need to parse <code>``</code>.

**Comment by leafo** [comment]
if it was a string then it would compile to `val(<<, val2)`, which is wrong. The interpolated code would need some sort of context based on the code that is being interpolated.

I'm strongly against adding Lua interpolation. If there's any reason to add it, it's probably because MoonScript is missing syntax from Lua that can be easily added.

**Comment by ChickenNuggers** [comment]
@leafo what I meant by parsing it as a string is that the logic behind a string that only the quotes would be parsed. I didn't mean it compiling to a string.

**Comment by ludamad** [comment]
@ChickenNuggers The most sane default would be for Moonscript to assume Lua code is untouchable statements and assign them a value of nil if they need a value. The result would be something that could subtly break things and be useful in very niche scenarios. It would have some use to somebody, for sure, but @leafo is right that it's best done as a language improvement. As for the operators, there is no reason they couldn't just be added to Moonscript (behind a flag or not).

**Comment by branefreez** [comment]
I feel that allowing unparsed statements has the potential to help out at times.
If we leave alone anything between backticks, then we can write inline Lua code:
```moonscript
n = 2^32
while n > 1024
    n = n `>>` 1  -- `LUA` escapes the Lua code and inline-s is.
print "n = #{n}"  -- should print: n = 1024
```
Which would turn into:
```lua
n = 2^32
while n > 1024 do
    n = n >> 1
end
print("n = " .. n)
```
Note: being that the code between backticks is Lua and is unparsed, the moonscript parser should not allow 
```moonscript
foo `op`= expr  -- meaning `foo = foo op (expr)
```
because we have no idea that `op` will produce valid Lua code with the given Lua syntax.
E.g.
```moonscript
n = 10
n `do`=3
```
makes nonsense code:
```lua
n = 10
n = n do 3  -- ERROR: expected 'end' to end 'do' on line 2
```

**Comment by ChickenNuggers** [comment]
@leafo General consensus says that this is overall a bad idea; are we able to close the issue now?

**Comment by leafo** [comment]
@branefreez it's not that simple, moonscript compiles different code depending on what type of code in is in a certain place. It has no way of knowing if the interpolated code evaluates to a function, or is an operator, for example. Since moonscript works with a abstract syntax tree, I can't just leave it alone, it has to be compiled into something in its context.

Here's what I would expect to see from two different examples, that look the same to the moonscript compiler:

```moon
a `<<` b --> a << b
a `hello` b --> a(hello(world))
```
 
In any case, I'm going to close this because I don't think it's that useful. If something is missing please open an issue.

**BTW** `<<` is in the language. If you can give me an example of something you actually want to use this feature for I'll think about it some more.
