### ISSUE TITLE
(Concept) binding parameters with stubs

### ISSUE THREAD

**Issue by s-ol** [leafo/moonscript#204]
Currently you can use the `\` to bind a method to a class instance to pass it around.

I find it weird that calling a function sometimes needs a `!` and sometimes doesn't; a more orthogonal way would be this in my opinion:

```moonscript
    object.property          -- get value of property
    object.method            -- get value of method
    object.method 1, 2, 3    -- bind method to parameters (but not to object)

    object.property!         -- error
    object.method!           -- invoke method with no parameters / unbound
    object.method! 1, 2, 3   -- invoke method with parmameters (but not object)

    object\property          -- error
    object\method            --  bind method to object (like current syntax)
    object\method 1, 2, 3    -- bind method to object and parameters
  
    object\property!         -- error
    object\method!           -- invoke method with one parameter
    object\method! 1, 2, 3   -- invoke method with object and parmeters
```
In practice it would look something like this:

```moonscript
    print = print "[LEVEL 1]" -- prefix everything with a fixed string
    class Player
      new: (@name, @health=100) =>
      takeDamage: (reason, dmg=10) =>
        print! "#{@name} took #{dmg} damage from #{reason}"
        @health -= dmg
        @die! reason if  @health < 0

      die: (reason) =>
        @dead = true
        print "#{@name} died from #{reason}"

      ply = Player! "Jane"
      
      burn = (player) ->
        timer.every_second! player\takeDamage "burning", 20

      timer.in_minutes! 2, player\win
      print! "survive burning for 2 minutes to win this level!"
```
Of course this would deviate from the CoffeScript syntax a lot, but I really like the orthogonality with this syntax.

**Comment by nonchip** [comment]
also it would break every moonscript code existing and prevent you from using generator functions, because:
```moonscript
    gen=(a)-> (b)->a+2*b
    gen 5 3 -- currently returns 11
    -- in your syntax:
    gen! 5! 3 -- maybe could be guessed because type(5)~="function"
    -- but:
    gen2= (fun)-> (a) -> fun a*2
    gen2 print 5 -- prints 10
    -- in your syntax:
    gen2= (fun)-> (a) -> fun! a
    gen2! print! 5 -- calling print and handing it's return value (nil) to gen2, not what we want.
```

so, please DON'T! it'll literally break everything, and also everything is perfectly fine now, because:


> Currently you can use the \ to bind a method to a class instance to pass it around.

true.

> I find it weird that calling a function sometimes needs a ! and sometimes doesn't

false. it never needs a `!`. "function argument" means call. "function" means function. "function!" means call. perfectly fine syntax sugar rule: "every function call without arguments can be written by appending ! instead of () to distinguish a call from the function itself"

also, that's exactly what it is: syntax sugar. calling a function in moon means:

```moonscript
    fun(arg,...) -- "strict" syntax w/ args
    fun arg,... -- "nice/lazy" syntax w/ args
    fun() -- strict w/o args
    fun! -- lazy w/o args, because "fun" without any operator would just be the function itself and "()" are wasting 1 byte :P
```

also, argument binding works just fine in moon, to use your example (which i never would, because you're redefining a stdlualib function without any reason, which is one of the worst practices ever heard of. PLEASE rename it in production code):

```moonscript
    do local print=(...)-> _G.print "[LEVEL 1]", ... -- works but horrible style
    printlvl=(...)-> print "[LEVEL 1]", ... -- works and good style, also notice how "argument binding", as you call it, is just "define a function to call something", which is pretty much almost EVERYTHING you do in moon
```

so instead of breaking the whole language in an attempt to apply the logic of a "syntax sugar rule" in reverse, just stick to the syntax providing you with the required features anyway.

**Comment by S0lll0s** [comment]
> maybe you wanna take another look at http://moonscript.org/reference/? you seem to misunderstand some operator concepts there.

I am fairly certain I don't, you just completely missed my point. I should've explained that, but by `object\property          -- error` I didn't mean that should throw an actual error, I meant to illustrate that that is not the way it is intended to be used.

Also this issue is prefixed with `(Concept)` because I full-well realize that this is probably not going to happen and break compatibility for absolutely everything. I still wrote this as a discussion of [language orthagonality](https://en.wikipedia.org/wiki/Orthogonality_(programming)) (which you might want to read up on, since apparently you do not know what I am talking about).
>```
>    -- in your syntax:
>    gen2= (fun)-> (a) -> fun! a
>    gen2!! print! 5 -- calling print and handing it's return value (nil) to the return value (function) of gen2, not what we want.
>```

if you just used `gen2` the way you designed it it would work:

    (gen2! print)! 5

yes, this requires parenthesis, but the example is highly unrealistic anyway.

> > I find it weird that calling a function sometimes needs a ! and sometimes doesn't
>
> false.

I realize that you can call every function with parenthesis in the same way, but avoiding exceptions is what orthagonal language design is all about. "!" is an exception, my syntax removes it. 

> also, argument binding works just fine in moon, to use your example (which i never would, because you're redefining a stdlualib function without any reason, which is one of the worst practices ever heard of. PLEASE rename it in production code):

I am aware, but this is a tiny example.

> also, remember when you said in your first sentence that you LIKE method binding and how exactly this syntax is NOT an error? so if it's a good (which I second) and perfectly logic (which both moon and Lua second) thing, why do you want to introduce an error to prevent you from using it?

had you taken the time to actually read what I wrote you would have noted that I actually gave multiple examples for using method binding:

    object\property          -- error
    object\method            --  bind method to object (like current syntax)
    object\method 1, 2, 3    -- bind method to object and parameters

like I said above, "error" was a bad choice for that line, but what it was meant to show is that the `\` is clearly inteded to be used with functions (or tables that support a `__call` metamethod, for that matter).

**Comment by deathbeam** [comment]
And what about ruby-style method calling?

```moonscript
object\method -- call the method, no ! needed
method = object.method -- threat method like lua does, so bind it there with classis self first param
property = object.property -- normal property
object\property  -- error, or nothing, arguable
```

**Comment by nonchip** [comment]
@S0lll0s 

>  I meant to illustrate that that is not the way it is intended to be used.

well, it is. just not for calling, but it's a valid statemen

> "!" is an exception, my syntax removes it.

that's true, but moonscript tries to be nice there and provide you with syntax sugar, so it's intentional. i guess if you want a strict language, moon might be just the wrong choice. because also the whole line decorator and table comprehension syntax isn't really required but saves you a bunch of coding.

if you want your lua-like lang to be more strict/spartan/small/etc, i'd suggest lua.


@deathbeam 

>      method = object.method -- threat method like lua does, so bind it there with self as first param

that's not how lua does it. lua just assigns the function if you do that, without any binding. lua doesn't even have a method binding facility, because you can do it yourself (`function bound(...) object:method(...) end`).

>     object\property  -- error, or nothing, arguable

how about binding the property's first arg to the object like moon does right now? cause you just can't know if it's a property or a method at compile time.


Sorry, but I just don't understand why you want to break every moon code out there just because moon tries to be too nice by providing you with syntax sugar.

**Comment by deathbeam** [comment]
Sorry, wrong word choice. Yes, I mean to assign it. And I think alowwing this

```moonscript
object\method
```

For calling the one arg method and making this

```moonscript
object\method!
```

deprecated but still present for backwards compatibility until next major release. But I do not agree with that original idea by using `!` everywhere which would break nice syntax for classes:

```moonscript
item = Item(10, 10) -- looks good and clear
item = Item! 10, 10 -- unclear and weird
item = Item 10, 10 -- unclear only
```

**Comment by nonchip** [comment]
@deathbeam 

> allowing this `object\method` for calling

this will break any existing code that uses such syntax when implicitly returning a bound method. so please don't. also there's no real need for it, because you just have to append an exclamation mark and get wonderful invocation syntax that's even implemented right now ;)

> making this `object\method!` deprecated

why? I don't understand why you want to get rid of syntax sugar in a lang like moon. we've got line decorators and list comprehensions and everything, why dump out this one feature just cause some users don't want to remember the very simple rule "name! expands to name()"?

> item = Item 10, 10 -- unclear only

not really, just uncommon, but once you know the syntax, it's logical.

**Comment by S0lll0s** [comment]
> that's true, but moonscript tries to be nice there and provide you with syntax sugar, so it's intentional. i guess if you want a strict language, moon might be just the wrong choice. 

orthogonal does not mean strict. method binding is just syntactic sugar aswell, even in my proposal.

> if you want your lua-like lang to be more strict/spartan/small/etc, i'd suggest lua.

 my proposal in fact introduces new options, like binding parameters to functions. It does not cut down on features, it cuts down on syntax exceptions while extending the langauges features.

**Comment by deathbeam** [comment]
@nonchip
Moonscript current version is only 0.2.* so adding features that breaks some backwards compatibility is fine as language is still evolving. Also, I am person who likes to have possibility to do one things only one way (see f.e. Python) and `!` syntax sugar is very specific to one param methods. Optional parenthesis is good thing, but to have single specific case where it is not optional is a bit weird.

**Comment by nonchip** [comment]
@S0lll0s 

> orthogonal does not mean strict. method binding is just syntactic sugar aswell, even in my proposal.

then I don't really understand why method binding is something you want, while aliasing `fun!` for `fun()` isn't. because method binding is also just an "alias" of `obj\method` for `(...)->obj\method ...`.

> my proposal in fact introduces new options, like binding parameters to functions. It does not cut down on features, it cuts down on syntax exceptions while extending the langauges features.

that's true, but binding function parameters already is a thing, just without any sugar. and you do cut down on features, because a syntax being used right now should be considered a feature.

@deathbeam I'd argue breaking compatibility is always a thing to avoid unless you have good reasons, and imho "I don't like syntax X because it's redundant" isn't a very good reason, cause you can always opt to (and/or dictate to in a coding style guide for your project) just not use it.

also https://github.com/search?utf8=%E2%9C%93&q=language%3AMoonScript&type=Repositories&ref=advsearch&l=MoonScript shows about 150 projects on github using moon right now, do you really break them all just cause moon's version number is pretty low? I wouldn't and I would actually decide to not follow the upstream if @leafo would decide to drop compatibility to so many projects (including lapis and LÖVE, the most important moon depending projects imho) just because 2 users don't like redundancy.

**Comment by deathbeam** [comment]
LÖVE do not depends on MoonScript. But also strictly sticking to something isn't always the best choice. Anyway, it was just my 2 cents and I do not wanted to open new issue for that so I used this one to share my opinion. That feature what I reccomened is the last thing I miss from MoonScript (as I tried a lot of scripting languages and I must say I would always choose MoonScript above all of them).

**Comment by S0lll0s** [comment]
> then I don't really understand why method binding is something you want, while aliasing fun! for fun() isn't. because method binding is also just an "alias" of obj\method for (...)->obj\method ....

like I said before, because that syntax is a very specific exception that can easily be avoided.

> and you do cut down on features, because a syntax being used right now should be considered a feature.

Surely you will agree that my new syntax allows the same instructions to be written with approximately equal syntax complexity whilst also introducing a way to shorten some recurring patterns in a strramlined fashion that is well-integrated with the rest of the syntax without introducing new syntactical complexity.

> I'd argue breaking compatibility is always a thing to avoid unless you have good reasons, and imho "I don't like syntax X because it's redundant" isn't a very good reason, cause you can always opt to (and/or dictate to in a coding style guide for your project) just not use it.

While backwards compatibility is important to keep if possible, it should not hold development and "innovation" back. @leafo is not linus torvalds and moonscript is not the Linux kernel. Semantic versioning is a thing and version 1.* *should* actually even break compatibility according to semver.

The python3 release also broke nearly every python project ever; but noone is forced to upgrade their interpreter/compiler and migrate their code.

**Comment by nonchip** [comment]
@S0lll0s 

> LÖVE does not depend on MoonScript.

true, but it supports it, and many LÖVE projects use it.

@deathbeam 

> like I said before, because that syntax is a very specific exception that can easily be avoided.

as can e.g. line decorators:
```moonscript
    print "hey" if true
    -- vs 
    if true then print hey
```

> Surely you will agree that my new syntax allows the same instructions to be written with approximately equal syntax complexity whilst also introducing a way to shorten some recurring patterns in a strramlined fashion that is well-integrated with the rest of the syntax without introducing new syntactical complexity.

i agree your syntax is fine to a degree (at least from the parser's point of view, from mine `fun! args` does seem more illogical than `fun args`), but I don't see how the existing one fails to be, and I strongly disagree deprecating an existing syntax is "well integrated with the syntax", because it isn't (cause it breaks it).

> While backwards compatibility is important to keep if possible, it should not hold development and "innovation" back.

true, but as I said, I don't see how the current syntax is holding anything back.

> @leafo is not linus torvalds and moonscript is not the Linux kernel.

yeah, and that is no argument. breaking compatibility isn't bad because Linus doesn't want it, but Linus doesn't want it because it's bad.

> Semantic versioning is a thing and version 1.* should actually even break compatibility according to semver.

also true, but that doesn't mean we have to break such a fundamental syntax as function invocation. maybe change some moon stdlib function instead if you insist on breaking stuff to get an excuse for releasing 1.x

> The python3 release also broke nearly every python project ever; but noone is forced to upgrade their interpreter/compiler and migrate their code.

also true. and that's while I will not follow that change, should it ever get into upstream.

Sorry, but you're the first person mentioning having any problems with that syntax to me, so maybe you just want to fork moon for yourself and let others decide if they like your change or not?

**Comment by S0lll0s** [comment]
>Sorry, but you're the first person mentioning having any problems with that syntax to me, so maybe you just want to fork moon for yourself and let others decide if they like your change or not?

FFS I don't have any problems with the current syntax, this is a discussion on proper language design.

**Comment by nonchip** [comment]
@S0lll0s 

>  this is a discussion on proper language design.

but well, this is a discussion on proper orthogonal language design, as you said yourself earlier, which moon does not claim to be.

I agree to you that e.g. lua should follow those principles, being a language that explicitely omits any feature you could code yourself, but moon does not claim to follow them, so why break compatibility to make it do so? if you want an orthogonal lang, moon simply isn't for you. same if you want a strictly typed lang.

**Comment by ChickenNuggers** [comment]
@leafo can you close this?

**Comment by leafo** [comment]
Interesting idea, but I want to avoid breaking changes.
