### ISSUE TITLE
Destructuring with single-line 'for' fails

### ISSUE THREAD

**Issue by ghost** [leafo/moonscript#236]
This parses:
```moon
for {:file, :args} in *options.runFiles
  runFile file, args 
```
But this doesn't:
```moon
runFile file, args for {:file, :args} in *options.runFiles
```
```
Failed to parse:
 [107] >>    runFile file, args for {:file, :args} in *options.runFiles
```

**Comment by branefreez** [comment]
I believe that the second argument it being misread. Instead of being read correctly, it is looking for a comprehension because of the for-loop decorator, but doesn't know what to do.

It seems to me that your current code is being read as a comprehension:
```moonscript
runFile file, {args for {:file, :args} in *options.runFiles}
-- or:
runFile file, [args for {:file, :args} in *options.runFiles]
```
But it may not know which you want (if you want it at all).

Try this:
```moonscript
runFile(file, args) for {:file, :args} in *options.runFiles
```
The parentheses should disambiguate for the linter.

**Comment by Kingdaro** [comment]
That didn't parse either. However, it _does_ parse without destructuring. with and without parentheses.
```moon
runFile info.file, info.args for info in *options.runFiles
```
...which is ultimately what I ended up going with, for the sake of one-linededness.

**Comment by leafo** [comment]
This is indeed broken, doesn't work for comprehensions as well:

```moon
[{a,b} for {a,b} in *thing]
```
