### ISSUE TITLE
Calling super from a mixin

### ISSUE THREAD

**Issue by pgkos** [leafo/moonscript#248]
Is there an idiomatic way of calling a super method from a mixin?

```moonscript
import mixin from require 'moon'

class Base
  foo: =>
    print 'foo'

class Mixin
  foo: =>
    super!
    print 'bar'

class Derived extends Base
  new: => mixin @, Mixin

d = Derived!
d\foo!  -- does not work
```

For now I have found the following workaround:
```moonscript
class Mixin
  foo: =>
    @__class.__parent.__base\foo!
    print 'bar'
```

**Comment by szensk** [comment]
I had a similar problem. Did something like `@@__parent.foo@`.

**Comment by leafo** [comment]
You'll have to reference the method directly. Be careful using `@__parent.hello` since it's not friendly with inheritance if supers are chained (might cause infinite loop). It's almost always better to mention the method of the class you want directly: `MyClass.hello`. Things are a bit tricky when using `mixin` though. A better implementation might make mixin methods take an additional argument of the class that was mixed.
