### ISSUE TITLE
moonc:254: attempt to compare number with nil

### ISSUE THREAD

**Issue by daurnimator** [leafo/moonscript#259]
While running `moonc -w` I moved a .moon file, this traceback came out:
```
/usr/lib/luarocks/rocks-5.3/moonscript/0.4.0-1/bin/moonc:271: /usr/lib/luarocks/rocks-5.3/moonscript/0.4.0-1/bin/moonc:254: attempt to compare number with nil
stack traceback:
	[C]: in upvalue 'watcher'
	/usr/lib/luarocks/rocks-5.3/moonscript/0.4.0-1/bin/moonc:271: in for iterator 'for iterator'
	/usr/lib/luarocks/rocks-5.3/moonscript/0.4.0-1/bin/moonc:279: in main chunk
	[C]: in ?
```

**Comment by ChickenNuggers** [comment]
I can't patch this right now, but I can later, so I'm going to brainstorm what's going to be done here. There's no automated file removal system, so that needs to be implemented every time the system is polled. This needs to be done before [line 254](https://github.com/leafo/moonscript/blob/master/bin/moonc#L254).
