### ISSUE TITLE
Fail to parse unless....elseif  structure

### ISSUE THREAD

**Issue by whileloopa** [leafo/moonscript#280]
I am using moonscrip-0.4.0 version.
unless block followed by elseif block cause parsing error.
```
 unless false
     print "hello"
 elseif true
     print "world"
```
unless....else structure can be parsed without problem.
```
unless false
    print "hello"
else
    if true
        print "world"
```
Is this intentional or a bug?

**Comment by Idyllei** [comment]
This is intentional. for example, at first glance, which if the following is easier to read?
```moonscript
if not bar
    print "foo"
elseif baz
    print "baz"
```
or
```moonscript
unless bar
    print "foo"
elseif baz
    print "baz"
```
Most likely the first. Why? Because the human mind finds it easier to remain in a positive context (if-elseif)\* rather than having to switch back and forth (if *not* - else if *not not*). Also, the if-elseif example makes one's intentions clear to the reader that the first case explicitly tests for the **opposite** (`not`) of the expression and the `elseif` test for an expression. 

\* In fact, that is the reason motivation works by telling yourself "I *will* do ____," instead of "I will *not* do ____;" the sub-conscious works **only in the positive**.

`unless-else` *is* allowed because is carries less cognitive baggage. It's 'like':
```moonscript
if not bar
    print "foo"
elseif not not bar  -- `elseif bar` (the `not not` cancels out)
    print "bar"
``` 
which could be written more concisely as:
```moonscript
unless bar
    print "foo"
else
    print "bar"
```

(Note: I'm sorry if this is confusing, my mind is being bombarded with my overflowing schedule. I'll clean this up later if you would like.)

**Comment by leafo** [comment]
No plans to support `unless ... elseif`

**Comment by leafo** [comment]
This has been added in a841de51ab326101c6314b6b395e0cd1f70e85a3
