### ISSUE TITLE
'\' is weird syntax why not keep ':' and '='?

### ISSUE THREAD

**Issue by nightsailer** [leafo/moonscript#35]
I know MoonScript replace ':'  with '\'  to  call an instance method,  but I think it's sooooooo  weird. 
As most language, '\' meant escape. So, try to read:
file\read
vs
file.read
vs
file:read

When reading code, I think the first way is hardest.

and try these code:

obj1\method2 "\01\002\010\"

And, I don't think so use ':'  to assigning a value to key in a table is better than '='.

So, why not keep ':'  and '='  behavior?  
It's bad idea to change the operator behavior, it make hard to port code between Lua and Moonscript,
also  make people more confused.

**Comment by adderlan** [comment]
It troubles me that this single character is even an issue. Sure, it would be nice to have a richer set of symbols available, but one has to choose from the very limited set that's available on standard keyboards to even hope of getting any traction (which I hope changes at some point, because symbols are important). So as long as the meaning is clear, I won't get too hung up on the aesthetics.

What troubles me more however is that some people have suggested replacing it with **':'** and *then consider whitespace to decide its meaning*. **'\'** may be ugly, but its meaning is *very* obvious, and doesn't change when you indent/nest code. On the other hand, using **':'** in the way @nilnor and @tbastos suggest makes its meaning far less obvious, and changes it when you indent/nest code. So for nothing more than an aesthetic consideration people seem willing to limit the expressiveness/formatting of a language, make code more difficult to read, and raise the probability of generating hard to spot errors. Significant whitespace should be used to make code *more* readable, not less.

And this really, really bugs me, because if this is the sort of thing programmers are getting hung up on and driving their decisions, I'm gravely concerned for the future. Forget 'should', programmers *need* to be pragmatic. It's fundamental to the discipline. And while engineering always involves tradeoffs (for example, using symbols not included on a keyboard may increase clarity but decrease accessibility), this is not an example of such.

So good choice @leafo, and good luck with MoonScript.

**Comment by tbastos** [comment]
@adderlan MoonScript is *already* whitespace sensitive in a few places, in case you haven't noticed. But you're right, in retrospect my comment about pragmatism is off. I think there are *pragmatic* reasons why MoonScript should have kept ':' for method calling, namely the "barrier of entry" and code legibility for new users coming from vanilla Lua. This was my criteria when evaluating MoonScript a while back: can people who know Lua (and e.g. CoffeeScript) be expected to read MoonScript without many "wtfs"? The answer is debatable, but what troubles me is that some "wtfs" could have been avoided. But I don't want to contribute to the polemics so I'll delete my suggestion. Peace :)

**Comment by nilnor** [comment]
@adderlan I think that reducing it solely to a question about "aesthetics" is vastly over-simplifying it. People consider it "ugly", but I doubt that has much to do with the graphical appearance of the `\` character itself. Rather I believe it's a cognitive mismatch for most people, since most mainstream languages use the `\` operator for escape sequences and that makes it jarring.

As for it being a pragmatic choice, you could argue in both directions. Yes, there's a shortage of usable symbols, making it a pragmatic choice. And yes, the backslash is for a lot of people typically associated with different semantics, making it in my view a non-pragmatic decision. At the end of the day, many people consider it off-putting and it makes them less likely to consider Moonscript. It's been an issue for me, and as I've advocated the use of Moonscript to other people I've consistently gotten the same reaction - "looks nice, but the backslash thing? eew". It's a barrier to adoption, and recognizing this seems pragmatic to me.

Talking about keyboards, I've seen the "easy to type" argument being brought up a couple of times, While perhaps tangential to the larger issue, I just wanted to point out that it's highly dependent on the keyboard layout. I'm Swedish, and while the backslash is available on Swedish keyboard layouts, it's accessible through the RSI-inducing `alt gr + \` combination, both keys being located on the right hand side of the keyboard which makes it very uncomfortable to write. I personally use the US layout while coding, but as far as I can tell most people don't.

As for the proposal to change the meaning of `:` depending on whitespace, I recognize that it would limit the language somewhat in that it would not possible to for instance put the actual method after a new line. I don't see the whitespace sensitivity as an issue; as @tbastos pointed out Moonscript is already sensitive to whitespace. It wouldn't make the language harder to read for me, but that's a subjective issue. As for generating "hard to spot errors", that strikes me more as a theoretical issue than a practical one, but I'm interested to see examples where this would be a real issue.

**Comment by stevedonovan** [comment]
On Fri, Feb 13, 2015 at 9:04 AM, Nils Nordman <notifications@github.com>
wrote:

> language harder to read for me, but that's a subjective issue. As for
> generating "hard to spot errors", that strikes me more as a theoretical
> issue than a practical one, but I'm interested to see examples where this
> would be a real issue.
>

Well, here would be an example

t = {key1: value1, key2:value2}

If colon is overloaded, then there are two very distinct meanings here; the
second is a partially-applied method bound to key2, the first is an actual
key/value pair.  Here the flexibility of tables bites us, because it is
possible for this to compile correctly, and yet yield puzzling results!

So I think (on further thought) to learn to live with backslash -
aesthetics are relative, as has been pointed out.

The alternate way of doing this is to just use '=' in table constructors
;)  Not sure what the syntactical implications are.

**Comment by devast8a** [comment]
> If colon is overloaded, then there are two very distinct meanings here;
the
> second is a partially-applied method bound to key2, the first is an actual
> key/value pair.
As far as the parser is concerned it's easy to give method binding and
method
application two different symbols.

For example, you could keep \ for binding and have : only for method
application.
You still have a similar problem though

t = {key1: func1!, key2:func2!}

> The alternate way of doing this is to just use '=' in table constructors
> ;) Not sure what the syntactical implications are.
Well assignment isn't an expression, so you could...
But I'd much rather leave '=' open for assignment as an expression.

**Comment by nilnor** [comment]
On 02/13/2015 08:17 AM, Steve J Donovan wrote:
>
> Well, here would be an example
>
> t = {key1: value1, key2:value2}

Sure, that's the resulting semantic difference. But this strikes me as 
most often falling in the same general category as typos, etc. - might 
be hard to discover when reading the code, but will be readily apparent 
when actually executing the code. It's a bigger problem only if 
`key2:value2` is a valid method invocation, but presumably that case is 
not so common as to be a real issue.

**Comment by stevedonovan** [comment]
On Fri, Feb 13, 2015 at 9:43 AM, Nils Nordman <notifications@github.com>
wrote:

> be hard to discover when reading the code, but will be readily apparent
> when actually executing the code.


I find with dynamic languages that code needs to be clear and obvious,
since as humans we rely on static analysis. It also takes some training to
'see' the difference between ':' and ': '.  Of course, we have Tests, but
it saves time to catch things before running programs. At least \ is very
obvious.



> It's a bigger problem only if
> `key2:value2` is a valid method invocation, but presumably that case is
> not so common as to be a real issue.


It is a valid idiom in MS (unlike Lua) and binds the first argument of the
method to the object resulting in a function.  Most useful when providing
callbacks!

My question rather is why stick with colon for table constructors?  Just so
that MS looks like everyone else?

**Comment by nilnor** [comment]
> It is a valid idiom in MS (unlike Lua) and binds the first argument of the method to the object resulting in a function. Most useful when providing callbacks! 

Yes, I misread there, and I'm aware of what bindings are. Still, my points is that for most cases this would fail very visible at runtime, provided that `key2` is not a valid table.

> My question rather is why stick with colon for table constructors? Just so that MS looks like everyone else?

Now we're really talking about major changes :) 

That would have avoided some disambiquity. On the other hand, the short table syntax wouldn't work anymore, e.g. `key: foo` currently evaluates as a table, whereas one typically wouldn't expect `key = foo` to evaluate as a table at all. And if it did that would look weird, e.g. `my_func bar = foo` :)

**Comment by stevedonovan** [comment]
On Fri, Feb 13, 2015 at 10:12 AM, Nils Nordman <notifications@github.com>
wrote:

> That would have avoided some disambiquity. On the other hand, the short
> table syntax wouldn't work anymore, e.g. key: foo currently evaluates as
> a table, whereas one typically wouldn't expect key = foo to evaluate as a
> table at all. And if it did that would look weird, e.g. my_func bar = foo
> :)
>
>
Ah, and it's such a nice finger-friendly syntax that!   Language design is
hard, I can live with \

**Comment by hems** [comment]
lol, could we just use the classic "." and fix the other things instead of messing with Mr. Classic Dot ?

**Comment by devast8a** [comment]
Well ```.``` already means something else, you'd have to change it first.

**Comment by ludamad** [comment]
I like Moonscript very much and I consider it a nicer interface to LuaJIT. I think it's a bit sad that Moonscript wasn't more conservative in its changes in a sense, though. As it stands it is not a satisfying answer to "I like Lua, but I want a bit more syntactic sugar". I find myself avoiding Moonscript features that would make my code look alien to Lua programmers. Overall, I think from the strong thoughts on this topic that there is room in the niche space for a more conservative Lua-sugar language, but there is nothing objectively wrong with Moonscript's choices.

**Comment by hems** [comment]
indeed, there is nothing wrong with making it's own choices, and i love this idea.

but messing with Mr. Dot felt very weird to me and as @ludamad will look very alien, not only to lua programmers, but to any other programmer that might end up having to deal with the code without previously having some "training", which is very doable with other languages like coffee script ( as long as you don't cut a lot of corners in 1 line ).

**Comment by gsbhasin123** [comment]
i'd say `::` is a decent alternative

**Comment by Diegovsky** [comment]
just wanted to point out that in by ABNT2 (qwerty) keyboard the backslash sits to the left of the letter z. I know the ansi keyboard has it somewhere around the right part of the keyboard, making it a non issue. Tbf, I really think this layout's designers had the worst decisions taken. You should look it up to understand how dump it is.

it would be cool© if there was a digraph symbol (like `::` or `//`) intended for compatibility-only, no deprecation of the current and perfectly reasonable backslash operator. I wouldn't mind one bit if it were behind a compiler flag or whatever. It's just that this symbol specifically is really badly accessible in my keyboard.

Regarding which symbol to use, I think `::` is perfect because it is perfectly search-and-replace -able by automated tools while also being (I think) currently unused in the language.

All in all, I'm eager to start using MS and Lapis :)

**Comment by bpj** [comment]
Perl is far from dead. It has added features with every yearly release for the last fifteen years or so, and there are several new or updated modules on CPAN every day. It's native Unicode handling is still the best. Some other languages were sorely lacking in that department last I looked! That said I wasn't born this century, and neither was my youngest kid (although just barely!) Neither people nor programming languages drop dead at thirty years old.
